/**
 * Standard Synthetic Aircraft Scenarios & Profiles
 */

import { ScenarioDefinition } from '../types/simulation';

export const SIMULATION_SCENARIOS: ScenarioDefinition[] = [
  {
    id: 'cold-dark',
    title: 'Cold & Dark Cockpit',
    description: 'Aircraft parked at dispersal ramp. Battery off, engine shut down, canopy open, zero hydraulic pressure.',
    category: 'STARTUP',
    initialState: {
      altitudeFt: 39,
      speedKnots: 0,
      headingDeg: 90,
      onGround: true,
      engineRunning: false,
      gearDown: true,
      flaps: 'AUTO',
      fuelPercent: 90,
      weatherPreset: 'CLEAR_DAY',
    },
    objectives: [
      'Close and lock canopy',
      'Energize Battery and External Power Cart',
      'Verify 28V DC and 115V AC on electrical bus',
      'Verify Fuel Boost Pumps and Collector Pressure > 40 PSI',
      'Initiate Engine Crank & Start sequence',
      'Observe N2 spool up past 60% and generator take-off',
    ],
  },
  {
    id: 'ready-taxi',
    title: 'Ready for Taxi',
    description: 'Engine stabilized at Ground Idle (63% N2). Dual hydraulics 3000 PSI, avionics online, parking brake set.',
    category: 'STARTUP',
    initialState: {
      altitudeFt: 39,
      speedKnots: 0,
      headingDeg: 90,
      onGround: true,
      engineRunning: true,
      gearDown: true,
      flaps: 'AUTO',
      fuelPercent: 85,
      weatherPreset: 'CLEAR_DAY',
    },
    objectives: [
      'Release Parking Brake',
      'Advance throttle to 15% to initiate taxi roll',
      'Check differential braking and nosewheel steering',
      'Set Flaps to HALF (18°)',
      'Taxi into position on Runway 09',
    ],
  },
  {
    id: 'takeoff-roll',
    title: 'Takeoff Roll - Runway 09',
    description: 'Lined up on centerline of Runway 09 (3,200m). Systems nominal, cleared for immediate departure.',
    category: 'TAKEOFF',
    initialState: {
      altitudeFt: 39,
      speedKnots: 0,
      headingDeg: 90,
      onGround: true,
      engineRunning: true,
      gearDown: true,
      flaps: 'HALF',
      fuelPercent: 85,
      weatherPreset: 'CLEAR_DAY',
    },
    objectives: [
      'Advance throttle to Military Power or Afterburner',
      'Maintain runway centerline with rudder pedals',
      'At 145 KIAS, rotate gently to 10° pitch attitude',
      'Positive rate of climb - retract landing gear',
      'Accelerate through 250 KIAS and retract flaps',
    ],
  },
  {
    id: 'cruise-flight',
    title: 'Airborne Cruise (FL150)',
    description: 'Level flight at 15,000 ft, 380 KIAS (Mach 0.76). Performing navigation tracking and flight envelope maneuvers.',
    category: 'CRUISE',
    initialState: {
      altitudeFt: 15000,
      speedKnots: 380,
      headingDeg: 90,
      onGround: false,
      engineRunning: true,
      gearDown: false,
      flaps: 'AUTO',
      fuelPercent: 75,
      weatherPreset: 'CLEAR_DAY',
    },
    objectives: [
      'Hold altitude 15,000 ft within ±100 ft',
      'Track navigation waypoint WP-02',
      'Execute 4G sustained turn and monitor energy rate (Ps)',
      'Inspect engine telemetry and fuel balance',
    ],
  },
  {
    id: 'ils-approach',
    title: 'ILS Final Approach Runway 09',
    description: 'Established on 6 NM final approach at 2,500 ft. Intercept localizer and 3° glideslope.',
    category: 'APPROACH',
    initialState: {
      altitudeFt: 2500,
      speedKnots: 175,
      headingDeg: 90,
      onGround: false,
      engineRunning: true,
      gearDown: true,
      flaps: 'FULL',
      fuelPercent: 45,
      weatherPreset: 'OVERCAST_TURBULENCE',
    },
    objectives: [
      'Maintain airspeed 150-155 KIAS on approach',
      'Center localizer and glideslope needles on HUD/PFD',
      'Descend at 650-750 fpm sink rate',
      'Smooth flare at 30 ft AGL for touchdown',
      'Deploy speedbrake and apply wheel braking on rollout',
    ],
  },
  {
    id: 'emergency-flameout',
    title: 'Emergency: Engine Flameout',
    description: 'Engine flameout at 14,000 ft. High-pressure turbine spooled down. Glide for emergency restart or deadstick recovery.',
    category: 'EMERGENCY',
    initialState: {
      altitudeFt: 14000,
      speedKnots: 260,
      headingDeg: 90,
      onGround: false,
      engineRunning: false,
      gearDown: false,
      flaps: 'AUTO',
      fuelPercent: 50,
      weatherPreset: 'CLEAR_DAY',
    },
    objectives: [
      'Pitch for best glide speed (230 KIAS)',
      'Confirm fuel boost pumps ON and collector fuel available',
      'Select Engine Start Switch to START (Windmill/Airstart)',
      'Monitor N2 spooling past 20% and light-off EGT',
      'Divert towards Runway 09 if restart unsuccessful',
    ],
  },
];
